api = "0.4"

[buildpack]
id = "laraboot-io/laraboot-buildpacks-roadrunner"
name = "Laraboot RoadRunner Server Buildpack"
homepage = "https://github.com/laraboot-io/laraboot-buildpacks-roadrunner"

[metadata]
include-files = ["bin/build", "bin/detect", "bin/run", "buildpack.toml"]
pre-package = "./scripts/build.sh"

[metadata.default-versions]
road-runner = "2.1.1"

[[metadata.dependencies]]
id = "road-runner"
name = "road-runner"
sha256 = "73708674e479e7bfb8472ae0770e46df2a13a39ffdc287a9a42d617989dae64d"
source_sha256 = "8d2dd324ea27bffb30f86a0192ae50ff2bd1150836d6bd4689486b8cd9b64f06"
stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
source = "https://github.com/spiral/roadrunner/archive/refs/tags/v2.1.1.tar.gz"
uri = "https://github.com/spiral/roadrunner-binary/releases/download/v2.1.1/roadrunner-2.1.1-linux-amd64.tar.gz"
version = "2.1.1"

[[stacks]]
id = "io.buildpacks.stacks.bionic"
mixins = ["libexpat1"]

[[stacks]]
id = "org.cloudfoundry.stacks.cflinuxfs3"
